cookie:
  expiry_days: 30
  key: mykey
  name: null
credentials:
  usernames:
    admin:
      email: admin@integral-imi.com.br
      failed_login_attempts: 0
      first_name: Admin
      last_name: IMI
      logged_in: true
      password: $2b$12$Z9y5TduaSyJ1LS7mHMLCSOe.zuRi7v2.D00d4FM/UAIhBzS1y.1Ba
    
    # H2F_Alumar:
    #   email: h2f_alumar@integral-imi.com.br
    #   failed_login_attempts: 0
    #   first_name: H2F
    #   last_name: Alumar
    #   logged_in: false
    #   password: $2b$12$rPDzhmhRXyD58aoCbrspNOPWsAGgj/8M87LaQKg4MIrFnTJ1mIWI.